# Generated by Django 6.0.4 on 2026-05-01 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_cargar_sucursales'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='empleado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='asistencia.empleado'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('ENCARGADO', 'Encargado de sucursal'), ('EMPLEADO', 'Empleado')], default='ENCARGADO', max_length=12),
        ),
    ]
